### ISSUE TITLE
Unsupported SIGTRAP on Windows

### ISSUE THREAD

**Issue by djberg96** [david-mccullars/safe_timeout#3]
Saw this via github actions on Windows: `unsupported signal 'SIGTRAP'`.

With Ruby 2.7.2 on Windows 7 I see this for the list of available signals:
```
irb(main):001:0> Signal.list
=> {"EXIT"=>0, "INT"=>2, "ILL"=>4, "ABRT"=>22, "FPE"=>8, "KILL"=>9, "SEGV"=>11, "TERM"=>15}
```

Maybe use SEGV if TRAP isn't in the list?

**Comment by djberg96** [comment]
Upon digging into this, it will take a bit more effort to make it work. I'm tinkering with it, we'll see.

**Comment by david-mccullars** [comment]
Happy to take a look at any pull requests if you find a solution.  I'm afraid Windows wasn't ever really supported.

**Comment by djberg96** [comment]
I started working on it, but got stuck and sorta gave up for now: https://github.com/djberg96/safe_timeout/tree/windows

**Comment by david-mccullars** [comment]
I looked at it a bit today, but unfortunately I'm not really seeing a viable option.  Although `Signal.list` seems to indicate there are several signals available, only `KILL` seems to be truly supported, and that doesn't want to be trapped.  https://blog.simplificator.com/2016/01/18/how-to-kill-processes-on-windows-using-ruby/ provides some additional clarity on the problem.  It suggests making a system call to `taskkill`, but that still doesn't solve the trapping problem.

Sorry to not be able to support your use case, but this gem wasn't really designed with windows systems in mind.
